### ISSUE TITLE
Ubuntu Noble PSOL

### ISSUE THREAD

**Issue by Kerberus35** [eilandert/build_psol#3]
Hi Eilandert, 

Thank you very much for your work keeping pagespeed usable. If configured it works quite well, sad to see it abandoned. 
Previously you released PSOL for jammy etc. Do you have the PSOL for noble available? We prefer to build against the provided nginx (1.42.0) ourselves. The PSOL build does not work for me, as i run into compile issues. 

I dont see it in your repo as well, having the same problems?
https://deb.myguard.nl/pool/main/n/nginx/

Erg bedankt!

Groet

Jasper

**Comment by eilandert** [comment]
Hi Jasper ;-)

I couldn't get it to compile either, but you can use the jammy version. The library is compiled static, the only change it couldn't handle in the past is if a function in glibc gets deprecated and removed. Luckily that doesn't happen very often :)

Very strange though, the module is there on the filesystem, don't know why it isn't visible through the web.
https://deb.myguard.nl/pool/main/n/nginx/libnginx-mod-pagespeed_1.27.1-1myguard1~noble_amd64.deb

If you want an unfiltered view you can take http://deb.myguard.nl:8888/ that port is linked to a different nginx in case of problems (like this one)

Groetjes terug ;-)
Thijs

**Comment by Kerberus35** [comment]
Hi Thijs, 

Got it succesfully working for Ubuntu 24.04, Nginx 1.24.0, with the jammy PSOL. Thanks! 
Still some life in pagespeed.

For others who find this thread, this is the mentioned PSOL:
http://www.tiredofit.nl/psol-jammy.tar.xz

If you don't get a download but a page full of binary symbols, just save page as "psol-jammy.tar.xz". 
Or just curl and output to a file.
